#!/bin/bash
echo "finally Akash is going to U.S. with Dishu.. " >> tmp/Akash
printf "visa is necessary because he is an immigrant"
ls tmp/Akash
echo ".........."
cat tmp/Akash
echo "Thank you..see you soon"


