#!/bin/bash
echo "finally Akash is going to U.S. witH DISHU.. " >> tmp/Akash
printf "visa is necessary because he is immigrant"
ls tmp/Akash
echo ".........."
cat tmp/Akash
echo "Thank you..see you soon"


